Add 2nd shapeless post.
enear/enear.github.com pull request #5
Opened 2016-06-27 13:13 UTC by ragb

2016-09-23 14:46 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +This is the second instalment in a series of articles about [Shapeless][shapeless].
installment em vez de instalment - falta-te um l

2016-09-23 14:59 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +Further from [Shapeless][shapeless] off course, we we will use the [JAWN][jawn] Json parsing and `AST` library.
of course em vez de off course? Não tenho a certeza se querias dizer off course no sentido de fora de percurso mas se sim então está bem, mas ficou um pouco esquisito na minha opinião.

2016-09-23 15:03 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +What this essentially means is that instances of `Generic[T]` can convert back and fort  from `T`to `Repr` -- a generic representation of `T`. However two questions arise:
forth em vez de fort

2016-09-23 15:11 UTC, ragb commented
era of course. Mas itself fica melhor.

2016-09-23 15:16 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +What if we had specific types for all literals? For instance, a single type for the literal `1` which is a subtype of integer? You might think "ah, nice, good for you". Believe me, this will came use
this will be come in useful - em vez de - this will came useful

2016-09-23 15:34 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +* As analogous to HList's `HNil`, `CNil` marks the end of the type definition, and is used to stop recursion and to possibilitate proper type construction.
isto pode parecer mariquice mas enable proper type construction fica melhor do que possibilitate.

2016-09-23 15:35 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +* `At runtime if we have and instance of `Inl`we Know we are handling an instance of the "head" of the coproduct.
if we have an instance em vez de if we have and instance

2016-09-23 15:35 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +The derivation example bellow will make this all much clearer.
below em vez de bellow

2016-09-23 15:38 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +Shapeless `LabelledGeneric` is capable of generating a coproduct representation of a sealed trait hierarchy, being the possible values all the known children, tagged with its  class's name -- a label
having all the known children as the possible values, tagged with its class's name -- a labelled coproduct. Tou a corrigir a parte inicial porque parece-me pouco idiomático, mas é só uma sugestão.

2016-09-23 15:39 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +Although `CNil` should never be reached, we need an implicit `JsonWrites[CNil]` in ope, so the compiler can properly infer the write implicits (stop the recursion):
in ope? é suposto ser só ope? é um diminutivo de alguma coisa que eu não estou bem a ver ou está errado?

2016-09-23 15:40 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +The recursive case is easy, we add a `"$type"` field with the class's simple name so a desserializer can differentiate among types.
deserializer em vez de desserializer

2016-09-23 15:40 UTC, lmreis89 commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +It is quit similar to what we did with the `HList` above.
quite similar em vez de quit similar

2016-09-23 16:03 UTC, ragb commented
É o correcto, como estava ficava estranho apesar de se compreender.

2016-09-23 16:03 UTC, ragb commented
in scope lol

2016-09-23 16:06 UTC, ragb commented
Essa frase estava estupida, já clarifiquei

2016-09-27 12:58 UTC, jtjeferreira requested changes

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +Note the type of the `gen`variable: the inner type `Repr`is automatically derived for us. This `Generic.Aux` type might be strange for some. If you are not familiar with the Aux pattern, [this is a g
In the above scala snippet there is no reference to Generic.Aux but to Generic.Repr which is an usage of the Aux pattern

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +```scala
add a newline here so syntax highlight kicks in

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +Pay attention to the `Repr`type of the last expression. It is essentially a`HList` of the case class elements, each one refined wit the `FieldType` tagging type described above. Shapeless calls this
you are not referring the last expression, but the penultimate expression. at least the better way to check Repr type is on the penultimate one

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +    tailWrites: JsonWrites[Tail]): JsonWrites[FieldType[Key, Head] :: Tail] =
put the return type in the next line

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +*`:+:` is analogous to Hlist's '::` type constructor, however it can be either an `Inl`or `Inr`.
add space after * to properly render the bullet list. also the :: is not properly escaped

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +* We are not supposed to reach `CNil`, ever.
I didnt understand the eliminate method. add a description here

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +    JsonWrites[FieldType[Key, Head] :+: Tail] = JsonWrites[FieldType[Key, Head] :+: Tail] {_.eliminate({ head =>
improve indentation of this line by putting eliminate in next line ?

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +We already defined the conversion from `T` to its generic representation above, so it will be used as such (the new coproduce-related implicit will be peaked automatically).
replace coproduce-related by coproduct-related. replace peaked with picked

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +* Define how labelled products (case class) are to be processed. Cases for HNil and `FieldType[Key, Head] :: Tail`.
use plural (i.e case classes)

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +* Use the generic `T`representation to derive processing for `T -- `LabelledGeneric.Aux[T, Repr]`.
I dont understand the -- here. maybe typo?

2016-09-27 12:58 UTC, jtjeferreira commented on _posts/2016-06-27-bits-of-shapeless-2.md
> +[shpray-json-shapeless][srayJsonShapeless] is a very interesting case since the code is very clear and concise, and has some nice ideas and patterns for this sort of implementations.
replace [shpray-json-shapeless][srayJsonShapeless] with [spray-json-shapeless][sprayJsonShapeless]

2016-09-27 15:00 UTC, ragb commented
Done, when all is fine I’ll rebase it into a single commit.

2016-09-27 16:59 UTC, jtjeferreira approved these changes

2016-09-27 17:02 UTC, merged