Add Monads for the rest of us post
enear/enear.github.com pull request #9
Opened 2017-04-11 11:07 UTC by xplosunn

2017-04-12 10:03 UTC, ragb reviewed
Very good.

2017-04-12 10:03 UTC, ragb commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +The Option Monad has the purpose of abstracting the presence (or absence) of a value. The value may or not be there. You can think of it as type-safe nullification. Let’s start implement our Option p
start implementingg or start to implement (think both work)

2017-04-12 10:03 UTC, ragb commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +What do you do when you have a function, but no value? You do nothing. Having no value is having no value, regardless of the expected type. “flatMap” does nothing because we don’t have an argument fo
:)

2017-04-12 10:03 UTC, ragb commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +  def job: Job = ...
??? instead of ... (just to be fancy).

2017-04-12 10:03 UTC, ragb commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +var avgSalary: Int = null
var!!!!!!!!!!!!!!!!!!!

2017-04-12 16:38 UTC, pedropramos requested changes

2017-04-12 16:38 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +There’s a lot of articles around explaining functional programing and some of the theory and reasoning behind it. Most monad explanations are good if you understand the theory behind it. However, if
*There are

2017-04-12 16:38 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +When you first delve into the functional programing paradigm, there’s a shock. You come from a natural world where objects have a mutable state. You want food on your plate, you invoke “plate.put(foo
How about -> What about

2017-04-12 16:38 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +Well, that doesn’t look so transcending. It may be confusing at first, so let’s clarify. “A” is the type of the result of the block abstracted within the monad. F[A] is the type of our monad. Let’s s
entitled -> named

2017-04-12 16:38 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +trait Monad[A, F[A]] {
Porquê F[A] e não F[_]?

2017-04-12 16:38 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +sealed trait Bear[A] extends Monad[A, Bear[A]]
Sugiro mudar o Bear para algo que intuitivamente faça sentido ser parameterizado com um tipo A. Que tal Box[A]?

2017-04-13 10:51 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +The Monad trait also holds a couple methods. Let’s dive in on those. The “apply” method makes you able to build a Monad out of a value or a block. It’s a builder method. Then we have the “flatMap” me
(A) => F[B]  ->  (A) => Bear[B] (ou Box[B] se aceitares a minha sugestão anterior)

2017-04-13 10:51 UTC, pedropramos commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +trait Monad[A, F[A]] {
acho que a convenção até é ter os type constructors primeiro, portanto ficaria Monad[F[_], A]

2017-04-14 16:15 UTC, xplosunn commented on _posts/2017-04-03-monads-for-the-rest-of-us.md
> +trait Monad[A, F[A]] {
F[A] vs F[_]:
O F[_] implicaria mudar a assinatura do flatMap e todas as opções que encontrei me pareciam dificultar a explicação. 

Monad[F[_], A] vs Monad[A, F[A]]
A questão de seguir essa convenção ou não, quem ainda não está confortável com Monads pode também não estar confortável com Higher Kinded Types em geral. Por essa razão, prefiro tirar o underscore, por ser menos symbolo que precisa ser interpretado neste contexto. E para tirar o underscore, preciso de seguir esta ordem.

2017-05-08 09:52 UTC, merged